version: "3"
services:
  wdio-cucumber:
    build: .
    image: wdio-cucumber
    container_name: wdio-cucumber
    links:
      - selenium
    volumes:
      - ./src/:/usr/src/app/src
      - ./test/:/usr/src/app/test
      - ./babel.config.js:/usr/src/app/babel.config.js
      - ./wdio.conf.js:/usr/src/app/wdio.conf.js
      - ./wdio.BUILD.conf.js:/usr/src/app/wdio.BUILD.conf.js

  selenium:
    image: selenium/standalone-chrome-debug
    # image: selenium/standalone-firefox-debug
    expose:
      - "4444"
    privileged: true

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
