version: "3.7"
services:
  wdio-cucumber:
    build: .
    image: ffc-demo-acceptance-tests
    container_name: ffc-demo-acceptance-tests
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug
    privileged: true

  hub:
    image: selenium/hub