version: "3.7"
services:
  wdio-cucumber:
    build: .
    image: wdio-cucumber
    container_name: wdio-cucumber
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug
    privileged: true

  hub:
    image: selenium/hub